therapy_classes:
  - ANTI_TNF_INFLIXIMAB
  - ANTI_TNF_ADALIMUMAB
  - ANTI_TNF_GOLIMUMAB
  - ANTI_INTEGRIN_VEDOLIZUMAB
  - IL12_23_USTEKINUMAB
  - IL23_P19
  - JAK_INHIBITOR
  - S1P_MODULATOR
  - IL6_TRANS_SIGNALING
  - OTHER

